version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ›  dependencies"
      - "â˜•ï¸ js"

  - package-ecosystem: "npm"
    directory: "/docs/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ›  dependencies"
      - "â˜•ï¸ js"
      - "ğŸ“š documentation"

  - package-ecosystem: "npm"
    directory: "/example/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ›  dependencies"
      - "â˜•ï¸ js"
      - "ğŸ›¸ example"

  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "daily"
    labels:
      - "ğŸ›  dependencies"
      - "ğŸ¤– android"
