version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "ğŸ›  dependencies"

  - package-ecosystem: "gradle"
    directory: "/package/android/"
    schedule:
      interval: "daily"
    labels:
      - "ğŸ›  dependencies"
      - "ğŸ¤– android"

  - package-ecosystem: "bun"
    directories:
      - "/docs/"
    schedule:
      interval: "daily"
    labels:
      - "ğŸ›  dependencies"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"

  # - package-ecosystem: "bun"
  #   directory: "/package/"
  #   schedule:
  #     interval: "monthly"
  #   labels:
  #     - "ğŸ›  dependencies"
  #     - "â˜•ï¸ js"
  # - package-ecosystem: "bun"
  #   directory: "/example/"
  #   schedule:
  #     interval: "monthly"
  #   labels:
  #     - "ğŸ›  dependencies"
  #     - "ğŸ›¸ example"
  #     - "â˜•ï¸ js"
  # - package-ecosystem: "bun"
  #   directory: "/docs/"
  #   schedule:
  #     interval: "monthly"
  #   labels:
  #     - "ğŸ›  dependencies"
  #     - "ğŸ“š documentation"
  #     - "â˜•ï¸ js"
