version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "package/android/"
    schedule:
      interval: "daily"
    labels:
      - "ğŸ›  dependencies"
      - "ğŸ¤– android"
  - package-ecosystem: "npm"
    directory: "package/"
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ›  dependencies"
      - "â˜•ï¸ js"
  - package-ecosystem: "npm"
    directory: "docs/"
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ›  dependencies"
      - "ğŸ“š documentation"
      - "â˜•ï¸ js"
