version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ›  dependencies"
  - package-ecosystem: "gradle"
    directory: "/package/android/"
    schedule:
      interval: "weekly"
    labels:
      - "ğŸ›  dependencies"
      - "ğŸ¤– android"
  - package-ecosystem: "npm"
    directory: "/package/"
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ›  dependencies"
      - "â˜•ï¸ js"
  - package-ecosystem: "npm"
    directory: "/package/example/"
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ›  dependencies"
      - "ğŸ›¸ example"
      - "â˜•ï¸ js"
  - package-ecosystem: "npm"
    directory: "/docs/"
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ›  dependencies"
      - "ğŸ“š documentation"
      - "â˜•ï¸ js"
