name: Build Android

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-android.yml"
      - "package/android/**"
      - "example/android/**"
      - "package/bun.lockb"
      - "example/bun.lockb"
  pull_request:
    paths:
      - ".github/workflows/build-android.yml"
      - "package/android/**"
      - "example/android/**"
      - "package/bun.lockb"
      - "example/bun.lockb"

jobs:
  build:
    name: Build Android Example App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          java-package: jdk

      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-with-fps-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-with-fps-gradle-
      - name: Run Gradle Build for example/android/
        run: cd example/android && ./gradlew assembleDebug --no-daemon --build-cache

      # Gradle cache doesn't like daemons
      - name: Stop Gradle Daemon
        run: cd example/android && ./gradlew --stop

  build-no-frame-processors:
    name: Build Android Example App (without Frame Processors)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
          java-package: jdk

      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install
      - name: Remove worklets, skia and reanimated
        run: |
          bun remove react-native-worklets-core @shopify/react-native-skia react-native-reanimated --cwd example
          bun remove react-native-worklets-core @shopify/react-native-skia react-native-reanimated

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-without-fps-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-without-fps-gradle-
      - name: Run Gradle Build for example/android/
        run: cd example/android && ./gradlew assembleDebug --no-daemon --build-cache && cd ../..

      # Gradle cache doesn't like daemons
      - name: Stop Gradle Daemon
        run: cd example/android && ./gradlew --stop
