name: Notice new dependencies
on:
  - pull_request

jobs:
  notice_new_dependencies:
    name: Notice new dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check for new dependencies
        uses: hiwelo/new-dependencies-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
